### PR TITLE
Fix spelling 'CronEventSchedulerVertical'.

### PR DESCRIPTION
**Pull request by Void9711**
Fix spelling 'CronEventSchedulerVertical'.

### CODE REVIEW

**Comment by otto-dev** [comment]
This would be a breaking change, but this spelling mistake is so grievous and in-your-face that it makes the library a lot harder to take serious.

 (I'm not the maintainer)

**Comment by diabolicallabs** [comment]
I use Vertical in my projects. Early on I questioned Tim's use of Verticle in vert.x. There was a debate in the Google Group way back. The only reference I could find for Verticle was that it is a misspelling of Vertical. In fact, my Mac is telling me I should replace Verticle for Vertical right now.

**Comment by otto-dev** [comment]
I have checked your statement, but it's definitely a spelling mistake, without question. The spelling `vertical` is never used for vertx `verticles` anywhere in the documentation, neither could I find any other projects that do so. If you need a reference, search `vertx.io` for both words, and compare the number of matches:

DeepinScreenshot_select-area_20191202112452
Compare:
DeepinScreenshot_select-area_20191202112508

The only mentions of `vertical` in a vert.x context I could find were individual spelling mistakes in articles that otherwise broadly use the term `verticle` (in the same article).

**Comment by Void9711** [comment]
(´▽`)ﾉ It's exactly not a functional problem, so it doesn't matter then. In fact I use "verticle" like @otto-dev .

**Pull request closed without merging**
